name: Test

on: [push, pull_request]

jobs:
  Test:
    runs-on: ubuntu-latest
    name: Test chat
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Tests
        run: python -m unittest src.test